"use server"

import { revalidatePath } from "next/cache"
import { supabaseAdmin } from "@/lib/supabase/admin"
import { getCurrentUser } from "@/lib/supabase/server"
import { todayIso } from "@/lib/ai/temporal"
import { parseDateInput } from "@/lib/dates"
import { validateTrackerOutput } from "@/lib/agent/tracker-parse"
import { getMissionRun } from "@/lib/agent/runs"
import { trackEvent } from "@/lib/analytics/events"
import { tasksFromTrackerPlan, type NewPlanTask, type PlanTask, type TaskStatus } from "./types"

/**
 * Plan tasks (P1-03). Every action tolerates a database where migration 0026
 * is not applied yet: it returns `{ ok: false, error: "plan_table_missing" }`
 * instead of throwing, so pages render and buttons explain themselves.
 */

type Result<T = unknown> = ({ ok: true } & T) | { ok: false; error: string }

function tableMissing(error: { code?: string; message?: string } | null): boolean {
  return Boolean(error && (error.code === "42P01" || error.code === "PGRST205" || /plan_tasks/.test(error.message ?? "")))
}

export async function listPlanTasks(): Promise<{ tasks: PlanTask[]; available: boolean }> {
  const user = await getCurrentUser()
  if (!user) return { tasks: [], available: true }
  const { data, error } = await supabaseAdmin
    .from("plan_tasks")
    .select("*")
    .eq("user_id", user.id)
    .order("due_date", { ascending: true, nullsFirst: false })
    .order("position", { ascending: true })
  if (error) {
    if (!tableMissing(error)) console.error("listPlanTasks:", error)
    return { tasks: [], available: !tableMissing(error) }
  }
  return { tasks: (data ?? []) as PlanTask[], available: true }
}

async function insertTasks(userId: string, rows: NewPlanTask[]): Promise<Result<{ inserted: number }>> {
  if (rows.length === 0) return { ok: true, inserted: 0 }
  const { data, error } = await supabaseAdmin
    .from("plan_tasks")
    .insert(rows.map((r) => ({ ...r, user_id: userId })))
    .select("id")
  if (error) return { ok: false, error: tableMissing(error) ? "plan_table_missing" : error.message }
  revalidatePath("/plan")
  revalidatePath("/dashboard")
  return { ok: true, inserted: data?.length ?? 0 }
}

/** Save the tracker step of a persisted agent run as tasks (idempotent per run). */
export async function savePlanFromRun(runId: string): Promise<Result<{ inserted: number; already: boolean }>> {
  const user = await getCurrentUser()
  if (!user) return { ok: false, error: "unauthorized" }

  const { data: existing, error: existingErr } = await supabaseAdmin
    .from("plan_tasks")
    .select("id")
    .eq("user_id", user.id)
    .eq("source_run_id", runId)
    .limit(1)
  if (existingErr) return { ok: false, error: tableMissing(existingErr) ? "plan_table_missing" : existingErr.message }
  if (existing && existing.length > 0) return { ok: true, inserted: 0, already: true }

  const run = await getMissionRun(runId, user.id)
  if (!run) return { ok: false, error: "run_not_found" }
  const step = run.steps.find((s) => s.tool === "tracker" && s.status === "completed" && s.text)
  if (!step) return { ok: false, error: "no_completed_plan_step" }

  const today = todayIso()
  const validated = validateTrackerOutput(step.text!, { todayIso: today })
  if (!validated.ok) return { ok: false, error: `plan_invalid:${validated.reason}` }

  const rows = tasksFromTrackerPlan(validated.plan, { source: "agent", sourceRunId: runId, todayIso: today })
  const res = await insertTasks(user.id, rows)
  if (res.ok) trackEvent(user.id, "plan_saved", { source: "agent", tasks: res.inserted })
  return res.ok ? { ok: true, inserted: res.inserted, already: false } : res
}

/** Save a plan generated by the standalone tracker tool (client passes the JSON). */
export async function savePlanFromTracker(planJson: string): Promise<Result<{ inserted: number }>> {
  const user = await getCurrentUser()
  if (!user) return { ok: false, error: "unauthorized" }
  if (planJson.length > 200_000) return { ok: false, error: "plan_too_large" }
  const today = todayIso()
  const validated = validateTrackerOutput(planJson, { todayIso: today })
  if (!validated.ok) return { ok: false, error: `plan_invalid:${validated.reason}` }
  const res = await insertTasks(user.id, tasksFromTrackerPlan(validated.plan, { source: "tracker", todayIso: today }))
  if (res.ok) trackEvent(user.id, "plan_saved", { source: "tracker", tasks: res.inserted })
  return res
}

export async function addPlanTask(input: {
  title: string
  description?: string
  due_date?: string
  deadline_kind?: "official" | "personal" | "estimate"
  priority?: "high" | "medium" | "low"
  category?: string
  source?: "manual" | "scholarship" | "application" | "program"
  scholarship_id?: string
  application_id?: string
  program_id?: string
}): Promise<Result<{ inserted: number }>> {
  const user = await getCurrentUser()
  if (!user) return { ok: false, error: "unauthorized" }
  const title = input.title?.trim()
  if (!title) return { ok: false, error: "Укажи название задачи" }
  const due = parseDateInput(input.due_date)
  if (due === null) return { ok: false, error: "Дата не распознана — введи ДД.ММ.ГГГГ" }
  return insertTasks(user.id, [
    {
      title,
      description: input.description?.trim() || null,
      category: input.category || "prep",
      priority: input.priority ?? "medium",
      status: "todo",
      due_date: due || null,
      deadline_kind: input.deadline_kind ?? "personal",
      month_label: null,
      position: 0,
      source: input.source ?? "manual",
      source_run_id: null,
      application_id: input.application_id ?? null,
      scholarship_id: input.scholarship_id ?? null,
      program_id: input.program_id ?? null,
    },
  ])
}

export async function setPlanTaskStatus(id: string, status: TaskStatus): Promise<Result> {
  const user = await getCurrentUser()
  if (!user) return { ok: false, error: "unauthorized" }
  const { error } = await supabaseAdmin
    .from("plan_tasks")
    .update({ status, completed_at: status === "done" ? new Date().toISOString() : null })
    .eq("id", id)
    .eq("user_id", user.id)
  if (error) return { ok: false, error: tableMissing(error) ? "plan_table_missing" : error.message }
  revalidatePath("/plan")
  return { ok: true }
}

export async function updatePlanTask(
  id: string,
  patch: { title?: string; description?: string; due_date?: string; deadline_kind?: "official" | "personal" | "estimate"; priority?: "high" | "medium" | "low" }
): Promise<Result> {
  const user = await getCurrentUser()
  if (!user) return { ok: false, error: "unauthorized" }
  const row: Record<string, unknown> = {}
  if (patch.title !== undefined) {
    const t = patch.title.trim()
    if (!t) return { ok: false, error: "Название не может быть пустым" }
    row.title = t
  }
  if (patch.description !== undefined) row.description = patch.description.trim() || null
  if (patch.due_date !== undefined) {
    const due = parseDateInput(patch.due_date)
    if (due === null) return { ok: false, error: "Дата не распознана — введи ДД.ММ.ГГГГ" }
    row.due_date = due || null
  }
  if (patch.deadline_kind) row.deadline_kind = patch.deadline_kind
  if (patch.priority) row.priority = patch.priority
  const { error } = await supabaseAdmin.from("plan_tasks").update(row).eq("id", id).eq("user_id", user.id)
  if (error) return { ok: false, error: tableMissing(error) ? "plan_table_missing" : error.message }
  revalidatePath("/plan")
  return { ok: true }
}

export async function deletePlanTask(id: string): Promise<Result> {
  const user = await getCurrentUser()
  if (!user) return { ok: false, error: "unauthorized" }
  const { error } = await supabaseAdmin.from("plan_tasks").delete().eq("id", id).eq("user_id", user.id)
  if (error) return { ok: false, error: tableMissing(error) ? "plan_table_missing" : error.message }
  revalidatePath("/plan")
  return { ok: true }
}
